### ISSUE TITLE
[Self-Host] Availability of a Pre-Built Playwright Image for Firecrawl

### ISSUE THREAD

**Issue by ronivaldo** [mendableai/firecrawl#1322]
**Describe the Issue**  
We are unsure whether a pre-built Playwright image is available for Firecrawl. Currently, the docker-compose configuration references the Playwright service as shown below, but the image field is left undefined (like the  commented-out build instruction):

```yaml
name: firecrawl

x-common-service: &common-service
  ...
  image: ghcr.io/mendableai/firecrawl
  ...

x-common-env: &common-env
  ...

services:
  playwright-service:
    image: ?????  # build: apps/playwright-service-ts
    environment:
      PORT: 3000
      PROXY_SERVER: ${PROXY_SERVER}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      BLOCK_MEDIA: ${BLOCK_MEDIA}
    networks:
      - backend
...
```

**To Reproduce**  
Steps to reproduce the issue:  
1. Configure the environment with the provided docker-compose file.  
2. Attempt to start the Firecrawl project without building the Playwright service from source.  
3. Observe that the Playwright service cannot start properly due to the undefined image.  
4. Error logs indicate that the image for the Playwright service is missing.

**Expected Behavior**  
A pre-built Playwright image should be available for self-hosting so that users can deploy the service without needing to build it from source.

**Additional Context**  
Having a pre-built Playwright image available would greatly simplify the self-hosting process by eliminating the need to build from source. Is there a pre-built image available for the Playwright service, or are there plans to release one soon? Any insights or guidance on this matter would be appreciated.
